### ISSUE TITLE
City field is being generated with undefined

### ISSUE THREAD

**Issue by hebertpaziam** [haterapps/fake-data#10]
I'm using the extension for **chrome** on **windows**.
The browser's locale is **pt-BR**.

When I try to generate a city, the value comes with a person name concatenated with `undefined`, like
 _Ricardoundefined_ or _undefined Muriloundefined_

- ![image](https://user-images.githubusercontent.com/18744762/136491017-58bca5e9-b624-40cf-b636-418739c398a6.png)
- ![image](https://user-images.githubusercontent.com/18744762/136491069-14593d2c-6cb5-4ee0-ab8c-883c1ab3147f.png)

**Comment by hebertpaziam** [comment]
a suggestion I give is to develop an algorithm adapting part of the material from this repository:

https://github.com/felipefdl/cidades-estados-brasil-json/blob/master/Cidades.json

**Comment by haterapps** [comment]
Hello,

Thank you for letting me know. I will look into this and come back with an update once it's fixed as soon as possible.

Fake Data uses by default the generated data from [faker.js](https://github.com/marak/Faker.js/) library, which seems to suffer from the same problem with the pt-BR language.


Also, not that much related to this, but if you need real city + address + zip code combinations for Brazil, Fake Data Ultra subscription can generate that.

**Comment by haterapps** [comment]
Hello,

The last update of Fake Data (v. 3.11.0) should fix this issue. It's already available for Chrome and Firefox. Please let me know if it works as expected now.


Thanks!
