### ISSUE TITLE
Update Faker.js link

### ISSUE THREAD

**Issue by stefan-evernest** [haterapps/fake-data#11]
On the [help page](https://github.com/haterapps/fake-data/wiki/Help-Page#custom-codes) there is a link to the [old Faker.js repository](https://github.com/marak/Faker.js/).

Since this project is deleted/not maintained anymore there is now an 'official' community maintained fork at https://github.com/faker-js/faker - so I guess it would be helpful to update the link on the wiki page

**Comment by haterapps** [comment]
Yes, indeed. I updated the link on the help page. I will update the one inside the extension on the next update.

Thanks!

**Comment by emrox** [comment]
That was fast - Awesome!

(I cannot resolve issues here, but I guess you can)
