### ISSUE TITLE
[Announcement] Transition of Fake Data to the new Google MV3 API

### ISSUE THREAD

**Issue by haterapps** [haterapps/fake-data#12]
## UPDATED 2024-05-24

Starting with version 4.9.0, the Chrome build will be released with MV3. If you're having any issues with your custom codes, please report them.

---

## UPDATED 2022-03-29
Read more details about MV3 migration and how it will work on the following link:
https://docs.fakedata.pro/writing-code/mv2-to-mv3-migration.html

Install the BETA version of Fake Data that runs on MV3 and help identify issues or bugs in your workflow earlier:
https://chrome.google.com/webstore/detail/fake-data-beta/cgdofifkggagondhlalkbfpdgneifkkk

---

# Important changes are coming!

Starting with January 2023 Google will require all Chrome extensions to be released with their new API, called MV3 (Manifest version 3). This will be a requirement for all extensions in the web store as well as the ones that are sideloaded, otherwise they will stop working in latest versions of the browser.

You can see more about the timeline [here](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/).

<br />

## What does this mean for Fake Data?

Because the transition from MV2 to MV3 is big and with significant changes, a lot of the code will be rewritten and adapted for the changes that are coming, so we can all be able to continue using Fake Data as before.

<br />

## What does this mean for users?

One of the huge breaking changes that MV3 brings is that **extensions can no longer execute remote code** as easily as before. While this may sound good in theory and will stop malicious extensions to execute code that is not bundled within them, it will also prevent legit uses of remote code.

Unfortunately, for Google, "remote code" does not mean only the code is downloaded from a remote server and then executed by the extension. It also means any code that is not bundled with the package. 

In Fake Data's case, it means that features like "Custom Generators", "fields with Custom Code", "Before and After callbacks", and "Loaded Libraries" will stop working as it's considered "remote hosted code".

But there is still hope. While MV3 restricts executing custom javascript code within its context, it still allows it to run in a sandboxed page that doesn't have access to any of the APIs or access to the DOM elements of the page you are in.

While I will do my best to make the transition as smooth as possible, with the best workarounds I can, there might be cases where the custom code you are using will need to be rewritten and adapted.

<br />

## What should you expect next?

- The Custom Codes feature will not go away, hopefully.
- There will be some changes to how things work in the scripts, but most of the use cases will be covered and any issue will be fixed along the way.
- Install the [BETA version](https://chrome.google.com/webstore/detail/fake-data-beta/cgdofifkggagondhlalkbfpdgneifkkk) of the extension and test out your workflow. You can post here or by email any issues that you find, so when the final update comes, there will be no surprises.
- Read the [migration guide](https://docs.fakedata.pro/writing-code/mv2-to-mv3-migration.html) to learn more about how the javascript code will be executed in the new MV3 version of Fake Data, and see the updates that you will need to apply to your code in order to keep it working.

<br />

## Conclusion

Since these changes are big and will need a lot of work, there will be less updates to Fake Data in the first months of this year, unless there are breaking issues or very small fixes. 

In order to be kept updated with this, the best way would be to subscribe to this thread so you will receive updates as they will be posted.

Thank you for understanding!

**Comment by haterapps** [comment]
Update on the new Fake Data migration to MV3:

You can install a BETA version for Fake Data from this link (Chrome only for now):
https://chrome.google.com/webstore/detail/fake-data-beta/cgdofifkggagondhlalkbfpdgneifkkk

Read more details about how the MV3 will work under the hood and what changes you will need to make in your code:
https://docs.fakedata.pro/writing-code/mv2-to-mv3-migration.html

Keep in mind that the beta version is a completely separate extension. Do not uninstall your current stable version because you will lose your data. You can temporarily disable the stable extension, so you don't have 2 versions at the same time, and you can quickly resume using it without losing anything.

There are still many things to do and multiple features that are somehow broken in this beta version. You can post here any problems that you find (either in this thread or create a new issue) so I can fix them in the next beta release.

**Comment by haterapps** [comment]
A new beta version of Fake Data has been published.
https://chrome.google.com/webstore/detail/fake-data-beta/cgdofifkggagondhlalkbfpdgneifkkk

 This version includes a lot of fixes related to the MV3 migration, like:

- loaded libraries should work as expected now (background and foreground libraries are now replaced by sandbox libraries in MV3 versions of Fake Data)
- more improvements to custom codes
- better DOM interaction between sandboxed frame and main page
- a lot of other bug fixes and errors that were occurring in the previous beta

Please test your custom codes and loaded libraries with the latest Beta, and let me know if there is anything that needs to be fixed.

## An update on what is coming up next
This beta version is most likely the last one. There will still be small fixes here and there, but if nothing major comes up, there will be no more betas released (unless requested).

The stable version of Fake Data will soon get an update with some new features added and a few bug fixes. The updates for the stable version will continue to be released under MV2 until later this year when it will be switched to the new MV3.

The next stable version of Fake Data will also have all the MV3 codebase merged into it, so hopefully nothing that is working now will break after this huge merge, fingers crossed. 🤞

**Comment by allanlaal** [comment]
please keep a normal branch for Firefox users (and powerusers soon to be migrating to Firefox) :)

**Comment by haterapps** [comment]
Yes, that's what I intend to do. Fake Data for Chrome will be migrated to MV3 next year, before June. For Firefox I will be keeping the MV2 version as long as possible.
Unfortunately, even Firefox will transition to MV3 at some point in the future, and then I will have to comply.

**Comment by allanlaal** [comment]
> even Firefox will transition to Manifest V3 at some point in the future

then we go https://github.com/WaterfoxCo/Waterfox  :)

**Comment by haterapps** [comment]
Ideally the transition to MV3 for Fake Data extension should be smooth, and with minimal to no changes that users will have to make to their custom code if using any.

Are you using something particular that you believe it might not work on MV3? Because I can take a look at that. Or did something broke on the beta version in case you tried that?

**Comment by EpicVoyage** [comment]
Thank you for all the hard work you put into this. I find it useful and have pointed several coworkers to this extension.

**Comment by haterapps** [comment]
Quick update here on MV3 transition for Fake Data extension: Starting with version 4.9.0 on Chrome, the extension will run with MV3.
Firefox and Edge will continue to work under MV2 until further announcements on their migration.

If you run into any problems with your custom generators after the migration please let me know either here on Github or at frustrations@haterapps.com
