### ISSUE TITLE
Unable to resolve "Cannont manage this element" issue

### ISSUE THREAD

**Issue by hjsemirdzhyan** [haterapps/fake-data#16]
The fill-ahead dropdowns I'm trying to work with on a particular form don't seem to be manigable by Fake Data. The field needs to be populated by one of the options in the dropdown but Fake Data fills it with random text instead. I'd like to deal with it with the "named field" feature since it has an identifier but when I right click on element to select "manage field", I instead get a text saying "cannon manage this element".

<img width="1542" alt="Screen Shot 2022-04-08 at 2 55 55 PM" src="https://user-images.githubusercontent.com/70782656/162537525-c27d4e1d-9743-418b-9e4a-2d62b0bbe31e.png">

<img width="1163" alt="Screen Shot 2022-04-08 at 2 59 28 PM" src="https://user-images.githubusercontent.com/70782656/162537635-d7476b82-3061-44d8-ba09-91e09fe12539.png">

**Comment by haterapps** [comment]
Hello,

That kind of dropdown is not a standard HTML form element. It's something very custom and Fake Data does not know how to handle it. You can though load an additional script inside Fake Data that will tell how to handle those dropdown.

Could you send me a link to the website so I can take a look and be able to write you a simple script that might work with that dropdown?

**Comment by hjsemirdzhyan** [comment]
The site requires a login to get anywhere that would have a drop down. I appreciate the response but no need. I'll just manually deal with the drop downs. The tool helps fill out most of what I need anyway.
