### ISSUE TITLE
MCE Editor

### ISSUE THREAD

**Issue by andreas-globi** [haterapps/fake-data#17]
Doesn't work in MCE rich text editor.

Alt+dblclick maximizes the window but does nothing else.
Context menu does not fill anything.

Verified on MCE website. MCE demo without context menu (to use the Chrome default with the FakeData option): https://www.tiny.cloud/docs/demo/comments-2/

**Comment by haterapps** [comment]
Hello,

Unfortunately, Fake Data does not work with MCE or any other WYSIWYG editors at this moment.

If you are comfortable with writing js code, you might be able to extend Fake Data and have it handle custom elements and editors. You can find a tutorial here on how to start doing this:
https://docs.fakedata.pro/writing-code/register-custom-elements.html
