### ISSUE TITLE
birth month how?????

### ISSUE THREAD

**Issue by kerenbir** [haterapps/fake-data#2]
ho can this extension auto fill birth month? how?
![bth](https://user-images.githubusercontent.com/25560477/77774112-21e37880-707d-11ea-9b9e-b7f132738d9d.png)

**Comment by haterapps** [comment]
Hi,

Dropdown fields can be filled the same as normal fields.
Just use Cmd + Double Click (on macOS) or Ctrl + Double Click (on Windows and Linux). This shortcut will fill only the selected field.

You can also fill the entire form with Cmd + Shift + Double Click / Ctrl + Shift + Double Click.

If none of the above works, maybe there is something special about that particular form, in which case you can share the link to it.

**Comment by kerenbir** [comment]
hi try to sign up on yahoo mail mail.yahoo.com
and they ask for birth month

**Comment by haterapps** [comment]
I was able to fill the birth month without any problem. Below is a screen record with that:
[https://share.getcloudapp.com/E0uqvbP0](https://share.getcloudapp.com/E0uqvbP0)

Do you have any issues filling it?

**Comment by kerenbir** [comment]
how??
is there any special script for that

**Comment by kerenbir** [comment]
thank you i understand now.
i forgot to activate (Behavior for <select> dropdowns:)

**Comment by haterapps** [comment]
I'm glad you managed to make it work.
