### ISSUE TITLE
Using await for customer generators

### ISSUE THREAD

**Issue by SpuriousGer** [haterapps/fake-data#22]
I want to use a value from a previous generator, but it is an asnyc operation.

This one is not working for me:
```
const val = await fakeData.getLastGeneratedValue('asset_value');
return (Math.random() * val);
```

How can I get this implemented?

**Comment by haterapps** [comment]
Hello,

Using `await` directly is not yet supported, but you can return a Promise that contains an async function.

In other words, you can try this:

```javascript
return new Promise(async function(resolve) {
	const val = await fakeData.getLastGeneratedValue('asset_value');
	resolve((Math.random() * val));
});
```

**Comment by SpuriousGer** [comment]
Awesome, thanks a lot
