### ISSUE TITLE
Does not show the current URL

### ISSUE THREAD

**Issue by xyngfei** [haterapps/fake-data#23]
let's say I have the site 
https://mdbootstrap.com/docs/react/forms/input-fields/

put the custom script for id=form1 textbox to return the current UR
`return document.location.toString()`

However, when I tried to generate random test data, it does not show the current URL, any idea?

![image](https://user-images.githubusercontent.com/17619539/204211646-7a850c63-9440-4790-8e33-fd0b95523194.png)

**Comment by haterapps** [comment]
Hello,

You can use the following code to get the page url:

```javascript
return function() {
	return document.location.toString();
}
```

If you need to access elements from `window` or `document` objects that belong to the page you are browsing, you will need to return a function (as in the example above). You can find out more about this at the link below:
https://docs.fakedata.pro/writing-code/run-in-content-script.html


Thanks!

**Comment by xyngfei** [comment]
@haterapps thx for your suggestion, it works perfectly fine.
however, if I am trying to build-in JS lib, it cannot work again.


```
return function() {
    return document.location.toString(); + moment().format("yyyyMMDD");
}
```

**Comment by xyngfei** [comment]
I miss out [this part]( 
https://docs.fakedata.pro/writing-code/run-in-content-script.html#passing-variables-from-background-page-to-content-script)

It works together with the moment lib
