### ISSUE TITLE
Does it support react-select?

### ISSUE THREAD

**Issue by xyngfei** [haterapps/fake-data#25]
Hi 

How can I auto-fill up the id="react-select-9-input" drop-down list? 

https://react-select.com/home

**Comment by haterapps** [comment]
Hello,

React-select integration is supported as part of the Pro features. If you already have a Pro license, you will need to enable the integration in the settings page:
https://docs.fakedata.pro/how-to-use-fake-data/settings/developer-options/custom-integrations/react-select.html

**Comment by xyngfei** [comment]
Thx for ur feedback and glad to know that
