### ISSUE TITLE
Add a changelog when releasing a new version

### ISSUE THREAD

**Issue by jman-schief** [haterapps/fake-data#26]
Hi,

it would be useful to see a list of changes when upgrading the extension.

Thanks

**Comment by haterapps** [comment]
Hello,

You can see the changelog by opening the options page, then go to About -> Changelog.

I hope that helps!

<img width="896" alt="image" src="https://user-images.githubusercontent.com/44547639/213157931-a664bbe1-cb81-4289-b657-528a5fe61063.png">

**Comment by jman-schief** [comment]
ah that got me - the option page is not available when the extension is disabled :)

thanks
