### ISSUE TITLE
getLastGeneratedValue returns Promise (errors in documentation)

### ISSUE THREAD

**Issue by fireton** [haterapps/fake-data#28]
`getLastGeneratedValue` does not returns `string` but `Promise`. 

So I can't write in my custom generator code something like

`return fakeData.getLastGeneratedValue('full_name').toLowerCase().replace(' ', '.') + '@fakemail.com';`

instead I have to write

```
let email = fakeData.getLastGeneratedValue('full_name')
	.then(x => x.toLowerCase().replace(' ', '.') + '@fakemail.com');
return email;
```

**Comment by haterapps** [comment]
Hello,

Thank you for pointing it out. I updated the [documentation](https://docs.fakedata.pro/writing-code/fake-data-api.html) to make it more clear that the return value is a Promise which will resolve to a string (as this is intended).

Your code is correct. Alternatively, you can also write it like this:

```javascript
return new Promise(async resolve => {
	let full_name = await fakeData.getLastGeneratedValue('full_name');

	resolve(full_name.toLowerCase().replace(' ', '.') + '@fakemail.com');
});
```

**Comment by fireton** [comment]
Should I consider always returning `Promise `in my custom generators code, not strings?

**Comment by haterapps** [comment]
Pretty much all of the functions that handle generators will return a `Promise`. But from your custom code, it doesn't matter if you return a `string` or a `Promise`. Fake Data will handle both fine.
