### ISSUE TITLE
Ctrl + Double Click not working in Firefox

### ISSUE THREAD

**Issue by elpollitodiablo** [haterapps/fake-data#3]
Wow first issue! I feel honored

Steps:

- Use winows 10
- Install firefox 80.0.1 (64-Bit)
- Install Fake Data from FF Addon page
- Ctrl+Click a select box
- Select an item like a caveman

EDIT: Ctrl + Shift + Click works

**Comment by haterapps** [comment]
Hello,

Thank you for reminding me about this issue. Firefox was never able to catch either click or double click events on <select> elements.
However, I spent some time today and I was able to find a potential workaround for that. Can you update Fake Data to latest version 2.18.4, which should be already available on Firefox, and let me know if it's any better?

Also just to make sure we are on the same page, the default shortcut, unless you have changed it, is Alt + Double Click on Windows.

Thanks!

**Comment by elpollitodiablo** [comment]
> Also just to make sure we are on the same page, the default shortcut, unless you have changed it, is Alt + Double Click on Windows.

Nothing changed here.

This works now, thank you! 👍
