### ISSUE TITLE
'Company' data generator not working

### ISSUE THREAD

**Issue by johnpurser** [haterapps/fake-data#30]
Hey there, when I attempt to use the 'Company' data generator, nothing fills out.  Also, when I use the 'preview' button on the manage options, the preview doesn't work either.

![image](https://github.com/haterapps/fake-data/assets/8234611/fbebf28e-563d-47cb-bc9b-bbbaae74f6e6)

![image](https://github.com/haterapps/fake-data/assets/8234611/5ac5303a-f8a0-4665-ac10-a6f949ab9249)

**Comment by haterapps** [comment]
Hello,

This seems strange. So far I wasn't able to reproduce this issue. Did you change any setting for the "company" generator in the Generators options page, or everything is set on default? Also, on the settings page are you using a different language than english?
Also, is that Chrome, or a different browser? So I can test it on that browser as well.

**Comment by johnpurser** [comment]
Wow.  That was my fault.  I must have clicked the 'Custom Code' dropdown option at one time on the settings page.  I didn't have anything in there, but just having it set to that prevented the 'default behavior.'  

Thanks so much for getting back to me!
