### ISSUE TITLE
Please add Macedonian language as a choice to generate data in

### ISSUE THREAD

**Issue by vordan** [haterapps/fake-data#32]
Macedonian language is not listed in the dropdown Generator language in the General settings.
Faker.js supports it, so it should be possible

**Comment by haterapps** [comment]
Hello,

Thanks for pointing that out! I'll make sure to add it on the next update.

**Comment by haterapps** [comment]
Hello,

The Macedonian locale has been added in latest Fake Data v.4.8.5.

Please let me know if you encounter any issues.


Thanks!
