### ISSUE TITLE
[Feat] Remove from context menu?

### ISSUE THREAD

**Issue by BtM909** [haterapps/fake-data#33]
Could you add an option to remove the Fake Data context menu entry?

I only have one generator, and I can always use the extension by selecting it from the Extensions menu.

Thanks

**Comment by haterapps** [comment]
Hello,

Thank you for your suggestion! I might add this in a future update. Out of curiosity, is there any other reason you want the context menu removed, or is it just for aesthetics?

**Comment by BtM909** [comment]
It's a bit of aesthetics due to Chrome adding entries and the maximum height of the context menu (which includes a scroll now). And secondly, for the few times I use it, I'd rather then just click on the extension in the Chrome menu.

**Comment by haterapps** [comment]
Thank you for the confirmation! I will keep you updated here on this.

**Comment by haterapps** [comment]
Hello,

In the latest update of extension (v 4.9.3) you can now hide "Fake Data" button from context menu. You can find the option in Settings page.
https://docs.fakedata.pro/how-to-use-fake-data/settings/show-hide-context-menu-button.html

**Comment by BtM909** [comment]
Wow nice! Thanks for the quick turnaround 💯
