### ISSUE TITLE
Update faker.js?

### ISSUE THREAD

**Issue by latere-a-latere** [haterapps/fake-data#4]
Hi, I just noticed that the locale files of faker.js contain a lot more values than currently output by the addon.

I tried updating to the newest version myself by simply loading in a downloaded copy of faker.js as a background lib but this didn't seem to work _that_ well. It'd generate values, but I wasn't able to set the locale.

Is it possible to have the addon updated to use the latest version?

**Comment by haterapps** [comment]
Hello,

Sure, let me look into this and I will get back with an update.

**Comment by haterapps** [comment]
Ok, so I updated the faker.js and moment.js libraries to their latest versions, and published them in version 2.18.5 of Fake Data.

For Firefox this version should already be available, but for Chrome and Edge might take a day or two.

Once you update, let me know if this fixes the issues that you had.

**Comment by latere-a-latere** [comment]
Yup, the strings that were missing are showing up! Thanks a lot for the quick update!
