### ISSUE TITLE
Read part of site and do math to it.

### ISSUE THREAD

**Issue by m1chaelbarry** [haterapps/fake-data#9]
I want to take text from site, in inspector it looks like this:
`<label for="captcha">What is 3 + 10?</label>`
and add these two numbers and put them in text field.
How can i do it?

**Comment by haterapps** [comment]
Hello,

You can use the following code for the captcha input field:

```
return function() {
	var text = $('label[for="captcha"]').text();
	var result = eval(text.replace(/[^0-9\+\-\*\/]/g,''))
	return result;
}
```

Let me know if that works.

**Comment by m1chaelbarry** [comment]
> 
> 
> Hello,
> 
> You can use the following code for the captcha input field:
> 
> ```
> return function() {
> 	var text = $('label[for="captcha"]').text();
> 	var result = eval(text.replace(/[^0-9\+\-\*\/]/g,''))
> 	return result;
> }
> ```
> 
> Let me know if that works.

Thank you, it works perfectly!
